eas-test:
  stage: test
  image: node:alpine
  allow_failure: true
  before_script:
    - cd $(pwd)/escape-game
    - npm install -g expo-cli
    - npm install
  script:
    - echo "Testing the app..."
    - npx tsc
    - npx expo-doctor
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes: 
        - escape-game/**

eas-build:
  stage: release
  image: node:alpine
  variables:
    EAS_BUILD_PROFILE: preview
  before_script:
    - cd $(pwd)/escape-game
    - apk --update add git
    - npm install -g expo-cli eas-cli
    - npm install
  script:
    - echo "Building the app..."
    - eas build --platform android --profile preview --non-interactive --no-wait
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes: 
        - escape-game/**