image: node:alpine

# workflow:
#   rules:
#     - if: $CI_COMMIT_TAG
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm

before_script:
  - npm ci --cache .npm

eas-build:
  stage: build
  script:
    - apk add --no-cache bash
    - npx eas-cli build --platform all --non-interactive --no-wait
