# .gitlab-ci.yml
# workflow:
#   rules:
#     - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
#     - if: $CI_COMMIT_TAG
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - convert-rapport
  - deploy-rapport

convert-rapport:
  stage: convert-rapport
  # This stage was written by Sermeus Steven in an other project and is used here with his permission
  image:
    name: mfreeze/pandoc-iesn:mermaid-latest-ubuntu
    entrypoint: [""]
  script:
    - echo "Converting Markdown to PDF..."
    - echo "Using pandoc version $(pandoc --version)"
    - cd $(pwd)/docs
    - /usr/local/bin/build.sh -p xelatex -m -l -M -e -N -c -I -T -s IEEE.csl pdf rapport.md
    - mv ./rapport.pdf ../rapport.pdf
  artifacts:
    paths:
      - ./rapport.pdf

deploy-rapport:
  stage: deploy-rapport
  dependencies:
    - convert-rapport
  script:
    - echo "Deploying to GitLab Pages"
    - mkdir .public
    - cp ./rapport.pdf .public/index.pdf
    - mv .public public
  artifacts:
    paths:
      - public
  # only:
  #   - main

