# .gitlab-ci.yml

# workflow:
#   rules:
#     - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
#     - if: $CI_COMMIT_TAG
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
  - build
  - deploy

# Docs building
convert-pdf:
  stage: build
  # This stage was written by Sermeus Steven in an other project and is used here with his permission
  image:
    name: mfreeze/pandoc-iesn:mermaid-latest-ubuntu
    entrypoint: [""]
  script:
    - echo "Converting Markdown to PDF..."
    - echo "Using pandoc version $(pandoc --version)"
    - cd $(pwd)/docs
    - /usr/local/bin/build.sh -p xelatex -m -l -M -e -N -c -I -T -s IEEE.csl pdf rapport.md
    - mv ./rapport.pdf ../rapport.pdf
  artifacts:
    paths:
      - ./rapport.pdf

convert-html:
  stage: build
  # This stage was written by Sermeus Steven in an other project and is used here with his permission
  image:
    name: mfreeze/pandoc-iesn:mermaid-latest-ubuntu
    entrypoint: [""]
  script:
    - echo "Converting Markdown to PDF..."
    - echo "Using pandoc version $(pandoc --version)"
    - cd $(pwd)/docs
    - /usr/local/bin/build.sh -p xelatex -m -l -M -e -N -c -I -T -s IEEE.csl html rapport.md
    - mv ./rapport.html ../rapport.html
  artifacts:
    paths:
      - rapport.html
  only:
    - main

pages:
  stage: deploy
  dependencies:
    - convert-html
  script:
    - echo "Deploying to GitLab Pages"
    - mkdir .public
    - cp ./rapport.html .public/index.html
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - main

# App buiding

eas-build:
  stage: build
  image: node:alpine
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm
  before_script:
    - npm ci --cache .npm
  script:
    - apk add --no-cache bash
    - npx eas-cli build --platform all --non-interactive --no-wait
  # only:
  #   - main

