convert-pdf:
  stage: build
  # This stage was written by Sermeus Steven in an other project and is used here with his permission
  image:
    name: mfreeze/pandoc-iesn:mermaid-latest-ubuntu
    entrypoint: [""]
  script:
    - echo "Converting Markdown to PDF..."
    - echo "Using pandoc version $(pandoc --version)"
    - cd $(pwd)/docs
    - /usr/local/bin/build.sh -p xelatex -m -l -M -e -N -c -I -T -s IEEE.csl pdf rapport.md
    - mv ./rapport.pdf ../rapport.pdf
  artifacts:
    paths:
      - ./rapport.pdf
  only:
    changes:
      - docs/**

convert-html:
  stage: build
  # This stage was written by Sermeus Steven in an other project and is used here with his permission
  image:
    name: mfreeze/pandoc-iesn:mermaid-latest-ubuntu
    entrypoint: [""]
  script:
    - echo "Converting Markdown to PDF..."
    - echo "Using pandoc version $(pandoc --version)"
    - cd $(pwd)/docs
    - /usr/local/bin/build.sh -p xelatex -m -l -M -e -N -c -I -T -s IEEE.csl html rapport.md
    - mv ./rapport.html ../rapport.html
  artifacts:
    paths:
      - rapport.html
  only:
    refs:
      - main
    changes:
      - docs/**

pages:
  stage: deploy
  dependencies:
    - convert-html
  script:
    - echo "Deploying to GitLab Pages"
    - mkdir .public
    - cp ./rapport.html .public/index.html
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    refs:
      - main
    changes:
      - docs/**